  sidebar <-
    dashboardSidebar(width = 300,
  sidebarMenu(id='tabs',
                      conditionalPanel('input.hide > input.show',
                                        appButton(inputId = "show", label = NULL, icon = icon("eye"))),
    bsTooltip(id='show', 'Click to show the header', placement = "bottom", trigger = "hover",options = NULL),
    menuItem("Data", tabName = "data", icon = icon("th")),
    menuItem("Unique", tabName = "unique",icon = icon('line-chart'),
              badgeLabel = "analysis", badgeColor = "green"),
    menuItem("Duplicates", icon = icon('line-chart'), tabName = 'duplicates',
             badgeLabel = "analysis", badgeColor = "green"),
  # conditionalPanel('output.user_group == `ADMIN`',
    menuItem("Admin", icon = icon('unlock-alt'), tabName = 'admin',
             badgeLabel = "admin", badgeColor = "red"),

  shinyWidgets::awesomeRadio('data_source', 'Choose data source', choices = c("historic"),
                             selected = "historic", status = "danger"),
                selectizeInput("columns",label = "Choose columns to be shown",
                 choices= c("Name", "Vorname", "Strasse", "PLZ"),
                 selected = c("Name", "Vorname", "Strasse", "PLZ"),
                 multiple =T, options = NULL),
       fileInput('file_input', 'Choose file with data to be loaded', accept = c('.csv','.xlsx', '.xlsm')),
    # checkboxInput("showHot", "Show handsontable"),
             conditionalPanel("input.tabs == 'duplicates' | input.tabs == 'unique'",
                selectizeInput("grouping_vars",label = 'Select vars for duplicates detection',
                 choices= c("Name", "Vorname", "Strasse", "PLZ"),
                 selected = c("Name", "Vorname"),
                 multiple =T, options = NULL)),
conditionalPanel("input.tabs == 'duplicates'",
shinyWidgets::awesomeRadio('calc_mode', 'Choose calulation mode', choices = c("exact", 'fuzzy'),
                           selected = "exact", status = "danger"),
conditionalPanel('input.calc_mode == `fuzzy`',
            sliderInput('fuzzy', 'Define max allowed Levenshtein distance', min=0, max=0.3, value=0.05, step=0.01),
              appButton(inputId = "calc", label = "Calculate", icon = icon("box"))))

))